### ISSUE TITLE
Consider a switch to react.js

### ISSUE THREAD

**Issue by hugurp** [inofix/note-it-js#45]
investigate if integrating React is really a good idea (aka, leaving the vanilla js world).

Does it work with d3 and canvas?

**Comment by hugurp** [comment]
Research notes:

## Selected literature 
- https://www.smashingmagazine.com/2018/02/react-d3-ecosystem/
- https://hackernoon.com/how-and-why-to-use-d3-with-react-d239eb1ea274
- https://oli.me.uk/2015/09/09/d3-within-react-the-right-way/

## Thoughts
Re-writing the the current `note-it-js` app with react.js will be quite an amount of work.
It supposes having a good understanding of both d3 and react, not to forget note-it-js.

Both react and d3 are made for DOM manipulation and holding state (the data), which can be error prone, and needs a clear distinction in roles.

Right now, I am in favor of not switching to React, as the benefits are not clearly identifiable and quantifiable. It also represents an amount of work that won't go into new features, but in a new architecture (based on react Components).
Also, the current javascript code is working well and can be improved without adding new dependencies / libraries.

On the other end, react gives a way to organize code (in Components), and using it with vx (the d3 library), might help clarify note-it-js's logic, what is rendered in the DOM and when.

## Available/selected libraries
From these articles and some research on libraries working well with both d3 + react.
Most of them are made to take advantage of d3 as a "chart" creator (which is not).

It seems the winner is `vx`: https://github.com/hshoff/vx/

Vx is created by the maintainer (hshoff) of one of javascript's standard style guide (airbnb's https://github.com/airbnb/javascript).

A live example by this person: https://beta.observablehq.com/@hshoff/demo-of-vx-react-on-observable

This example works on this website, observablehq, which has been created my the creator of d3 (https://beta.observablehq.com/@mbostock).

I'm not 100% sure this library will allow to do everything that is made in the existing note-it-js, but its reusable and composable system of component (react's), might.

## Final thoughts

- what are we trying to achieve by inserting an other library, `react`?
- can we do that it without using it?
- if we use react, should we use vanilla `d3`, or with a library, `vx`?
- is a rewrite (with addition of 1 or 2 libraries) worth the effort, or should the same amount of time be spent in improving the existing application and adding new features?
- will a rewrite, to react + vx, help the note-it-js project? Ease to add new features and maintain, user/contributor adoption?

Would love your opinions.

**Comment by wieueberall** [comment]
Second your opinions on react! However, vanilla js seems to be outdated at first, but others than that it's pretty platform agnostic, which may be something worth to consider.

I guess if not rewriting would be the scope, but focussing on UX improvements, we should be pretty good to go. As far as I understand, the application currently lacks of a usable and intuitive UI/UX, so I would suggest three things:

1. ditch the rewrite plans, since Hugos stance on this issue is a good one!
2. focus on redesigning the application in terms of UI/UX.
3. Keybind all the things! (we totally need keybindings/keyboard shortcuts in that application)

I would say if we still were in a planning stage without already having a working application, we should've aimed for react, but since the project itself already exists as a vanilla-JS project, rewriting it outnumbers the effort of improving what we already got, in terms of it'll require a considerable amount of work throwing atomic design react magic on this!

**Comment by zwischenloesung** [comment]
Yeah, I also totally agree.

For the feature set I am quite happy actually, and I think the remaining enhancement tickets (e.g. #43, #10, #9, #23) can easily be added with the old implementation (i.e. w/o new frameworks and thus dependencies).

What I am mostly interested in, is to have a mouseless UI (#44), such that one can write down ideas as fast as they come to ones mind :) ... Either there is a very smart UI-framework providing exactly this and that can be pulled on the existing solution with very little effort, or we just have to implement the interactions from scratch, right?

**Comment by hugurp** [comment]
Thanks for the feedback!

I will look into improving the overall UX (from user on-boarding to proficiency) as well as mouse, mouse-less and touch usages.

Agreeing that a re-write is out of scope, and that react could give a nice developer experience but needs a re-write, I will close this issue, and work on the app with its existing code-base.

Cheers!
